### ISSUE TITLE
Error on loading inline web window

### ISSUE THREAD

**Issue by Yaushee** [ardittristan/VTTInlineWebviewer#31]
Hello,

The module used to work perfectly but now I'm getting an error when trying to load any saved window, and I can't figure out why (same error on a new world whith only this module and libcolor enabled):

![image](https://user-images.githubusercontent.com/7393968/178115774-d26b8a9f-41ce-4688-8dee-89c47bfcc8ff.png)

Send URL does nothing as well (no error even).

I whitelisted the files in Avast too...

**Comment by JohBalalaika** [comment]
I have the same problem. at least previously loaded links work correctly

**Comment by skepickle** [comment]
The problem is actually that the website "https://youtube-domains.ardittristan.workers.dev/" is returning "null" instead of a list of youtube domains. The module fetches the content of this site to compare to the destination url to determine if the destination is a youtube link [which is the InlineViewer.js:40]. So The module is not working because of that...

**Comment by Yaushee** [comment]
Good catch! I managed to make a temporary quick fix for saved links without compatibility Iframes, by changing line 184 of inlineviewer.js to this list of youtube domains I copypasted:

`fetch("https://pastebin.com/raw/GGPBknd7")`

"Send URL to players" is still not working for me though.

**Comment by ardittristan** [comment]
Looking into it! was on holiday
