### ISSUE TITLE
Usage Question

### ISSUE THREAD

**Issue by mckee14** [ardittristan/VTTInlineWebviewer#36]
As there is no wiki, I post my question as an issue. I have no idea about iframes, html and css.

Is there a way to remove the whole left menu bar of this site with the iframe option? https://www.avespfade.de/

Thanks and best regards,
Marc

**Comment by ardittristan** [comment]
you could try enabling compatibility mode and adding `#menu` (the id of the left menu bar in css) to the removed elements field. This only works with compatibility mode because normally sites can't interact with content in iframes.

P.S. There should be a help button when you open the settings for the module with some information!

**Comment by mckee14** [comment]
Thank you very much for your answer. And I tried the help menu, but for complete noobs it's not enough to succeed hehe...
