### ISSUE TITLE
Feature suggestion: Shared web view

### ISSUE THREAD

**Issue by caerandir** [ardittristan/VTTInlineWebviewer#6]
Hi ardittristan,
I just tried your webviewer module, and I like it! Something that would make it perfect for me would be if I would have a button "Show to Players" on top (like e.g. with Journal entries) and could thus have a predefined web view pop up on the players screen (ideally I can select which players see it). The icing on the cake would be if the players would even see if I change the webpage view, like if I would do a screen sharing. This would e.g. allow me to pan and zoom on a map and the players can follow me.
Cheers
Caerandir

**Comment by ardittristan** [comment]
1. [Showing to players is already possible via the top button of the webviewer menu](https://github.com/ardittristan/VTTInlineWebviewer#when-sending-popup-as-gm)
2. Selecting which players you send it to is a good idea, I'll add it when I have time!
3. Changing players view if you change view is sadly not possible because of security policies in browsers (you can't see anything except the initial url in iframes)

**Comment by caerandir** [comment]
OK, thanks for the feedback! Keep up the good work!
Remark on "Showing to players": It is clear that I can share any URL via this function by pasting/typing a URL, but it would be cool if I could also share pre-configured URLs, i.e. I set up a WebView following your scheme [\<site url>, <button/window name>, <font awesome icon name (optional)>, <compatibility mode (optional)>], which then gets an Icon in the GM HUD. It would be cool if I could open the webview via HUD, and then click "Show to players" (like with a journal entry) and the preconfigured URL shows up at the player's screen (as if I had send it by pasting it in the box like already possible).

**Comment by ardittristan** [comment]
That's a good idea! I'll add a button to the webviews to do that!
